import type {
  CategoryRecord,
  Json,
  TransactionEnrichmentPatch,
  TransactionIntent
} from "@/lib/db";

export interface NormalizedReviewSuggestion {
  categoryId?: string | null;
  categoryName?: string;
  confidence?: number;
  intent?: TransactionIntent;
  merchantName?: string;
  reason?: string;
  recurring?: boolean;
  sourceDetail?: string;
  sourceKind?: ReviewSuggestionSourceKind;
  sourceLabel?: string;
  signals: string[];
}

export interface ReviewSuggestionPatchResult {
  patch: TransactionEnrichmentPatch;
  suggestion: NormalizedReviewSuggestion;
}

export type ReviewSuggestionSourceKind = "openai" | "merchant-rule" | "deterministic" | "review-rule" | "unknown";

const transactionIntents = new Set<TransactionIntent>([
  "personal",
  "business",
  "shared",
  "reimbursable",
  "transfer"
]);
const providerDiagnosticSignals = new Set([
  "openai unavailable or returned no additional signals"
]);

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function cleanString(value: unknown) {
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

function cleanNumber(value: unknown): number | undefined {
  if (typeof value === "number" && Number.isFinite(value)) return Math.max(0, Math.min(1, value));
  if (typeof value === "string" && value.trim()) {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) return Math.max(0, Math.min(1, parsed));
  }
  return undefined;
}

function readString(record: Record<string, unknown>, keys: string[]) {
  for (const key of keys) {
    const value = cleanString(record[key]);
    if (value) return value;
  }
  return undefined;
}

function normalizeIntent(value: unknown): TransactionIntent | undefined {
  const direct = cleanString(value);
  if (direct && transactionIntents.has(direct as TransactionIntent)) {
    return direct as TransactionIntent;
  }

  const nested = asRecord(value);
  if ("value" in nested) return normalizeIntent(nested.value);
  return undefined;
}

function normalizeBoolean(value: unknown): boolean | undefined {
  if (typeof value === "boolean") return value;

  const text = cleanString(value)?.toLowerCase();
  if (text === "true") return true;
  if (text === "false") return false;

  const nested = asRecord(value);
  if ("value" in nested) return normalizeBoolean(nested.value);
  return undefined;
}

function normalizeCategory(value: unknown): Pick<NormalizedReviewSuggestion, "categoryId" | "categoryName"> {
  const directName = cleanString(value);
  if (directName) return { categoryName: directName };

  const field = asRecord(value);
  const fieldValue = asRecord(field.value);
  const valueName = cleanString(field.value);
  const categoryName =
    readString(fieldValue, ["name", "categoryName", "label"]) ??
    valueName ??
    readString(field, ["name", "categoryName", "label"]);

  if (!categoryName) return {};

  return {
    categoryId: cleanString(fieldValue.id) ?? cleanString(field.id) ?? null,
    categoryName
  };
}

function normalizeMerchant(value: unknown) {
  const direct = cleanString(value);
  if (direct) return direct;

  const field = asRecord(value);
  const fieldValue = asRecord(field.value);
  const valueName = cleanString(field.value);
  return (
    readString(fieldValue, ["normalized", "merchantName", "name"]) ??
    valueName ??
    readString(field, ["normalized", "merchantName", "name"])
  );
}

function normalizeSignals(value: unknown): string[] {
  return Array.isArray(value)
    ? value
      .map(cleanString)
      .filter((signal): signal is string => Boolean(signal))
      .filter((signal) => !providerDiagnosticSignals.has(signal.toLowerCase()))
    : [];
}

function nestedReason(value: unknown) {
  const field = asRecord(value);
  return readString(field, ["reason", "explanation"]);
}

function fieldSource(value: unknown) {
  return cleanString(asRecord(value).source);
}

function normalizeSuggestionSource(record: Record<string, unknown>): Pick<
  NormalizedReviewSuggestion,
  "sourceDetail" | "sourceKind" | "sourceLabel"
> {
  const provider = asRecord(record.provider);
  const providerKind = cleanString(provider.kind);
  const sources = [
    fieldSource(record.category),
    fieldSource(record.intent),
    fieldSource(record.merchantCleanup),
    fieldSource(record.recurring)
  ].filter((source): source is string => Boolean(source));

  if (providerKind === "openai" || sources.includes("openai")) {
    return {
      sourceDetail: "Generated by the configured OpenAI provider from safe transaction context.",
      sourceKind: "openai",
      sourceLabel: "OpenAI"
    };
  }

  if (providerKind === "mock") {
    if (sources.includes("merchant-rule")) {
      return {
        sourceDetail: "Matched a saved merchant rule before any model output.",
        sourceKind: "merchant-rule",
        sourceLabel: "Saved merchant rule"
      };
    }

    return {
      sourceDetail: "Generated locally from merchant, amount, Plaid category, and rule cues.",
      sourceKind: "deterministic",
      sourceLabel: "Deterministic heuristics"
    };
  }

  if (record.reason || normalizeSignals(record.signals).length > 0) {
    return {
      sourceDetail: "Created by review queue rules that flagged this transaction for human judgment.",
      sourceKind: "review-rule",
      sourceLabel: "Review rule"
    };
  }

  return {
    sourceKind: "unknown",
    sourceLabel: "No suggestion source"
  };
}

export function normalizeReviewSuggestion(value: Json): NormalizedReviewSuggestion {
  const record = asRecord(value);
  const category = normalizeCategory(record.category ?? record.categoryName);
  const intent = normalizeIntent(record.intent);
  const recurring = normalizeBoolean(record.recurring ?? record.isRecurring);
  const merchantName = normalizeMerchant(record.merchantCleanup ?? record.merchantName);
  const confidence =
    cleanNumber(record.confidence) ??
    cleanNumber(asRecord(record.category).confidence) ??
    cleanNumber(asRecord(record.intent).confidence) ??
    cleanNumber(asRecord(record.recurring).confidence);
  const reason =
    readString(record, ["reason", "explanation"]) ??
    nestedReason(record.category) ??
    nestedReason(record.intent) ??
    nestedReason(record.recurring);

  return {
    ...category,
    confidence,
    intent,
    merchantName,
    reason,
    recurring,
    ...normalizeSuggestionSource(record),
    signals: normalizeSignals(record.signals)
  };
}

export function reviewSuggestionFieldSummary(suggestion: NormalizedReviewSuggestion) {
  return [
    suggestion.merchantName ? "merchant" : null,
    suggestion.categoryName ? "category" : null,
    suggestion.intent ? "intent" : null,
    suggestion.recurring !== undefined ? "recurring" : null,
    suggestion.confidence !== undefined ? "confidence" : null
  ].filter((field): field is string => Boolean(field));
}

export function describeReviewSuggestionRefresh(
  before: NormalizedReviewSuggestion,
  after: NormalizedReviewSuggestion
) {
  const afterFields = reviewSuggestionFieldSummary(after);
  const beforeFields = reviewSuggestionFieldSummary(before);
  const beforeSource = before.sourceLabel ?? "unknown";
  const afterSource = after.sourceLabel ?? "unknown";
  const changedFields = afterFields.filter((field) => {
    switch (field) {
      case "merchant":
        return after.merchantName !== before.merchantName;
      case "category":
        return after.categoryName !== before.categoryName || after.categoryId !== before.categoryId;
      case "intent":
        return after.intent !== before.intent;
      case "recurring":
        return after.recurring !== before.recurring;
      case "confidence":
        return after.confidence !== before.confidence;
      default:
        return false;
    }
  });
  const sourceChanged = before.sourceKind !== after.sourceKind || before.sourceLabel !== after.sourceLabel;
  const prefix = beforeFields.length > 0 ? "Suggestion refreshed" : "Suggestion generated";
  const source = `Source: ${afterSource}.`;

  if (changedFields.length > 0) {
    return `${prefix}: updated ${changedFields.join(", ")}. ${source}`;
  }

  if (afterFields.length > 0) {
    return sourceChanged
      ? `${prefix}: source changed from ${beforeSource} to ${afterSource}.`
      : `${prefix}: no accept-ready fields changed. ${source}`;
  }

  return `${prefix}: no accept-ready fields were found. ${source}`;
}

function findCategoryId(categories: CategoryRecord[], categoryName: string) {
  const normalized = categoryName.trim().toLowerCase();
  return categories.find((category) => category.name.trim().toLowerCase() === normalized)?.id ?? null;
}

export function buildAcceptedReviewSuggestionPatch(
  aiSuggestion: Json,
  categories: CategoryRecord[],
  options: { reviewedAt: string }
): ReviewSuggestionPatchResult {
  const suggestion = normalizeReviewSuggestion(aiSuggestion);
  const patch: TransactionEnrichmentPatch = {
    reviewedAt: options.reviewedAt,
    source: "ai"
  };

  if (suggestion.merchantName) {
    patch.merchantName = suggestion.merchantName;
  }
  if (suggestion.categoryName) {
    patch.categoryName = suggestion.categoryName;
    const knownId = suggestion.categoryId && categories.some((c) => c.id === suggestion.categoryId)
      ? suggestion.categoryId
      : findCategoryId(categories, suggestion.categoryName);
    patch.categoryId = knownId;
  }
  if (suggestion.intent) {
    patch.intent = suggestion.intent;
  }
  if (suggestion.recurring !== undefined) {
    patch.isRecurring = suggestion.recurring;
  }
  if (suggestion.confidence !== undefined) {
    patch.confidence = suggestion.confidence;
  }

  return { patch, suggestion };
}

export function hasReviewSuggestionValue(suggestion: NormalizedReviewSuggestion) {
  return Boolean(
    suggestion.categoryName ||
    suggestion.intent ||
    suggestion.merchantName ||
    suggestion.recurring !== undefined ||
    suggestion.confidence !== undefined
  );
}
